################################################################################
################################################################################
###
###  This file is automatically generated. Do not change this file! Changes
###  will get overwritten! Change the source file for "setup.py" instead.
###  This is either 'packageinfo.json' or 'packageinfo.jsonc'
###
################################################################################
################################################################################


from setuptools import setup

def readme():
	with open("README.md", "r", encoding="UTF-8-sig") as f:
		return f.read()

setup(
	author = "Jürgen Knauth",
	author_email = "pubsrc@binary-overflow.de",
	classifiers = [
		"Development Status :: 5 - Production/Stable",
		"License :: OSI Approved :: Apache Software License",
	],
	description = "Collection of utility functions and classes to manage temporary data.",
	download_url = "https://github.com/jkpubsrc/python-module-jk-temporary/tarball/0.2019.12.26",
	include_package_data = False,
	install_requires = [
	],
	keywords = [
		"temp",
		"tempfiles",
		"temporary",
	],
	license = "Apache 2.0",
	name = "jk_temporary",
	packages = [
		"jk_temporary",
	],
	url = "https://github.com/jkpubsrc/python-module-jk-temporary",
	version = "0.2019.12.26",
	zip_safe = False,
	long_description = readme(),
	long_description_content_type="text/markdown",
)
